// Generated by CoffeeScript 1.9.2
var async;

async = require('odo-async');

module.exports = function() {
  return {
    exec: function(description, action, cb) {
      return async.delay(function() {
        return action(function() {
          if (cb != null) {
            return cb();
          }
        });
      });
    },
    ready: function(cb) {
      return cb(function() {});
    }
  };
};
