// Generated by CoffeeScript 1.9.2
module.exports = function(dispatcher) {
  var _timeout;
  _timeout = 1000;
  return {
    exec: function(description, action, cb) {
      var duration, interval;
      duration = 0;
      interval = setInterval(function() {
        duration += _timeout;
        return console.log("[odo-hub] " + description + " has been running for " + (duration / 1000) + " seconds");
      }, _timeout);
      return dispatcher.exec(description, action, function() {
        clearInterval(interval);
        if (cb != null) {
          return cb();
        }
      });
    },
    ready: function(callback) {
      return dispatcher.ready(callback);
    }
  };
};
