// Generated by CoffeeScript 1.9.2
var async;

async = require('odo-async');

module.exports = function() {
  var _inprogress, _next, _queue, _ready;
  _queue = [];
  _inprogress = false;
  _ready = [];
  _next = function() {
    var item;
    _inprogress = true;
    if (_queue.length === 0) {
      if (_ready.length === 0) {
        return _inprogress = false;
      }
      _queue.push({
        description: 'ready',
        action: _ready.shift()
      });
    }
    item = _queue.shift();
    return item.action(function() {
      if (item.callback != null) {
        item.callback();
      }
      return async.delay(_next);
    });
  };
  return {
    exec: function(description, action, cb) {
      _queue.push({
        description: description,
        action: action,
        callback: cb
      });
      if (!_inprogress) {
        return async.delay(_next);
      }
    },
    ready: function(callback) {
      if (!_inprogress) {
        return callback(function() {});
      }
      return _ready.push(callback);
    }
  };
};
