// Generated by CoffeeScript 1.9.2
var hub;

hub = require('./parallel');

hub.every('thing', function(e, cb) {
  console.log(e);
  return cb();
});

hub.emit('thing', 'weeee', function() {
  return hub.emit('thing', 'weeee2', function() {
    return console.log('done.');
  });
});
